
2020-02-02 20:11:53,004 INFO: errors [in c:\Temp\01_fyyur\starter_code\app.py:615]
2020-02-02 20:12:17,578 ERROR: Exception on /shows/create [GET] [in C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Temp\01_fyyur\starter_code\app.py", line 583, in create_shows
    form = ShowForm()
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\form.py", line 158, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\form.py", line 132, in process
    field.process(formdata)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\csrf.py", line 121, in _get_config
    raise KeyError(message)
KeyError: 'A secret key is required to use CSRF.'
2020-02-02 20:12:22,712 ERROR: Exception on /venues/create [GET] [in C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Temp\01_fyyur\starter_code\app.py", line 325, in create_venue_form
    form = VenueForm()
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\form.py", line 158, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\form.py", line 132, in process
    field.process(formdata)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\csrf.py", line 121, in _get_config
    raise KeyError(message)
KeyError: 'A secret key is required to use CSRF.'
2020-02-02 20:12:28,176 ERROR: Exception on /artists/create [GET] [in C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Temp\01_fyyur\starter_code\app.py", line 518, in create_artist_form
    form = ArtistForm()
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\form.py", line 158, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\form.py", line 132, in process
    field.process(formdata)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "C:\Users\musth\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_wtf\csrf.py", line 121, in _get_config
    raise KeyError(message)
KeyError: 'A secret key is required to use CSRF.'
2020-02-04 22:44:51,589 INFO: errors [in C:\Temp\01_fyyur\starter_code\app.py:621]
2020-02-04 22:45:37,021 ERROR: Exception on /venues [GET] [in c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 294, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'Show' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Temp\01_fyyur\starter_code\app.py", line 203, in venues
    venue_query = Venue.query.group_by(Venue.id, Venue.state, Venue.city).all()
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 517, in __get__
    mapper = orm.class_mapper(type)
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\base.py", line 441, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\base.py", line 420, in _inspect_mapped_class
    mapper._configure_all()
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\mapper.py", line 1337, in _configure_all
    configure_mappers()
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\mapper.py", line 3248, in configure_mappers
    mapper._post_configure_properties()
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\interfaces.py", line 196, in init
    self.do_init()
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\relationships.py", line 1913, in do_init
    self._process_dependent_arguments()
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\relationships.py", line 1975, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\relationships.py", line 1880, in entity
    argument = self.argument()
  File "c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 306, in __call__
    % (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Venue->Venue, expression 'Show' failed to locate a name ("name 'Show' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.Venue'> class after both dependent classes have been defined.
2020-02-05 00:10:23,339 INFO: errors [in C:\Temp\01_fyyur\starter_code\app.py:633]
2020-02-05 00:10:31,316 INFO: errors [in C:\Temp\01_fyyur\starter_code\app.py:633]
2020-02-05 00:10:48,962 INFO: errors [in C:\Temp\01_fyyur\starter_code\app.py:633]
2020-02-14 10:32:55,714 INFO: errors [in C:\Temp\01_fyyur\starter_code\app.py:625]
